spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/db_delivery_note'
    username: postgres
    password: '123456'
    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: 'true'
#  rabbitmq:
#    host: localhost
#    password: guest
#    port: 5672
#    username: guest
#    exchange: order-delivery.exchange
#    queue: delivery.queue
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    stream:
      bindings:
        orderDeliveryChannel:
          destination: order_delivery
          group: delivery
        deliveryChannel:
          destination: deleteDelivery
          group: order
        orderItemChannel:
          destination: updateOrderItemQuantity
          group: order
#    routingkey: delivery.routingkey
client:
  post:
    baseUrl1: 'http://localhost:8083'
    baseUrl2: 'http://localhost:8084'
logging:
  level:
    org:
      zalando:
        logbook: TRACE
server:
  port: 8085