spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/db_order'
    username: postgres
    password: '123456'
    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  rabbitmq:
#    host: localhost
#    password: guest
#    port: 15672
#    username: guest
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        ordersChannel:
          destination: order
          group: manager
        orderDeliveryChannel:
          destination: order_delivery
          group: delivery
        deliveryChannel:
          destination: deleteDelivery
          group: order
  output:
    ansi:
      enabled: ALWAYS
client:
  post:
    baseUrl: 'http://localhost:8084'
    baseUrl1: 'http://localhost:8082'
    baseUrl2: 'http://localhost:8081'
logging:
  level:
    org:
      zalando:
        logbook: TRACE
      hibernate: INFO
      springframework: INFO

server:
  port: 8083

