jwt:
  secret: secretkey
  token:
    validity: '180000'
server:
  port: 8086
client:
  post:
    baseUrl1: 'http://localhost:8081'
    baseUrl2: 'http://localhost:8082'
spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      zalando:
        logbook: TRACE