spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/db_manager'
    username: postgres
    password: '123456'
    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: manager.queue
    routingkey: manager.routingkey
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: nguyenquanghuyxd96@gmail.com
    password: mebnqhclfmcdgktl
    port: '587'
client:
  post:
    baseUrl1: 'http://localhost:8082'
    baseUrl2: 'http://localhost:8083'
    baseUrl3: 'http://localhost:8084'
    baseUrl4: 'http://localhost:8085'
server:
  port: 8081
