server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: manager
          uri: http://localhost:8081/
          predicates:
            - Path=/manager/**
        - id: store
          uri: http://localhost:8082/
          predicates:
            - Path=/store/**
        - id: order
          uri: http://localhost:8083/
          predicates:
            - Path=/order/**
        - id: item
          uri: http://localhost:8084/
          predicates:
            - Path=/item/**
        - id: delivery-note
          uri: http://localhost:8085/
          predicates:
            - Path=/delivery-note/**
  thymeleaf:
    check-template-location: true
    enabled: true
    prefix: 'classpath:/templates/'
    suffix: .html
