server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
#        - id: manager
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/manager/**
        - id: store
          uri: http://localhost:8082/
          predicates:
            - Path=/store/**
        - id: order
          uri: http://localhost:8083/
          predicates:
            - Path=/order/**
        - id: item
          uri: http://localhost:8084/
          predicates:
            - Path=/item/**
        - id: delivery-note
          uri: http://localhost:8085/
          predicates:
            - Path=/delivery-note/**
#        - id: auth
#          uri: http://localhost:8086/
#          predicates:
#            - Path=/auth/**
  thymeleaf:
    check-template-location: true
    enabled: true
    prefix: 'classpath:/templates/'
    suffix: .html
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: 'true'